### ISSUE TITLE
Customize Settings

### ISSUE THREAD

**Issue by bkonia** [gabfl/PHP-PSR-2-Fixer-Coda-Plugin#1]
Is there any way you could give us access to the CodeSniffer settings, so we can customize it? If it's too much work to build a UI, perhaps you could allow us to select a custom configuration file to load.

**Comment by gabfl** [comment]
HI @bkonia,

I don't think Coda's plugin structure is flexible enough to do that. But you can easily fork the project and edit https://github.com/gabfl/PHP-PSR-2-Fixer-Coda-Plugin/blob/master/PHP%20PSR-2%20Fixer.codaplugin/Contents/Resources/052BF6D4-518B-4210-B10D-EAF406F1473B/Support%20Files/rules.xml to set the rules you would like to use.

**Comment by bkonia** [comment]
Well, I guess that's one possible solution, but I don't like the idea of forking a project unless I'm intending to continue developing it. If you're intending to continue developing this, I'd rather just leave it in your hands.

Also, I don't agree with your statement that Coda's plugin structure isn't flexible enough. Have you seen the PHP & Web Toolkit plugin? I've attached a screen shot showing its preferences screen, which contains six tabs worth of settings. Seems to me, it should be possible to add a similar preference screen to your plugin, which would allow the user to configure the main settings in the GUI and also provide a file input where he could select a totally custom configuration file and/or a command box where he could enter the actual phpcs command, including any custom parameters.

![2017-05-01_15-31-32](https://cloud.githubusercontent.com/assets/2266423/25597524/e824c2a4-2e83-11e7-85aa-1648ed2134e4.png)

**Comment by gabfl** [comment]
I am sorry but I am not going to develop that feature for you. If you would like to do it yourself I encourage you to fork this repo.
